name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Run a one-line script
        run: echo '${{ vars.TEST_VARIABLE }}'

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Run a one-line script
        run: echo '${{ vars.TEST_VARIABLE }}'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo '${{ vars.TEST_VARIABLE }}'
